spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/three_meals_a_day?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
  username: root
  password: root